services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite's default port
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/index.html:/usr/src/app/index.html
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
      - ./frontend/tsconfig.node.json:/usr/src/app/tsconfig.node.json
      - ./frontend/vite.config.ts:/usr/src/app/vite.config.ts
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot reload
    stdin_open: true  # Enable interactive mode
    tty: true        # Enable terminal for better output

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - student_api_network
    depends_on:
      - frontend
      - api

  mongodb:
    image: mongo:latest
    container_name: mongodb2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - student_api_network

  api:
    build: ./fastapi_stud_mgmt_api
    container_name: fastapi_student_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb2:27017
      - DATABASE_NAME=student_management
      - JWT_SECRET_KEY=f586fa74d2d1ee31e4154729d1eea85530cc0fc4e0b4dbd3566a7d3ef025cca7
    volumes:
      - ./fastapi_stud_mgmt_api:/app
    networks:
      - student_api_network
    depends_on:
      - mongodb

networks:
  student_api_network:
    driver: bridge

volumes:
  mongodb_data:
  frontend_build:
